export const environment = {
  production: true,
  apiBaseUrl: "https://entz-henning.de:8080/damago/api/v1",
  apiAddressesUrl: "/address",
  apiEmailsUrl: "/email",
  apiInventoriesUrl: "/inventory",
  apiSchoolClassesUrl: "/school-class",
  apiLocationPersonUrl: "/location-person",
  apiLocationsUrl: "/location",
  apiPersonUrl: "/person",
  apiRoomUrl: "/room",
  apiModuleUrl: "/module",
  apiPersonAddressUrl: "/person-address",
  apiPersonRoleUrl: "/person-role",
  apiPersonSchoolClassUrl: "/person-school-class",
  apiRoleUrl: "/role",
  apiPersonPhoneUrl: "/person-phone",
  apiPhoneUrl: "/phone",
  apiPersonEmailUrl: "/person-email",
  apiEmailUrl: "/email",
};
